services:
    alfredoramos.share.listener:
        class: alfredoramos\share\event\listener
        arguments:
          - '@alfredoramos.share.helper'
        tags:
            - { name: event.listener }

    alfredoramos.share.helper:
        class: alfredoramos\share\includes\helper
        arguments:
          - '@config'
          - '@template'
          - '@language'
          - '@controller.helper'
          - '%core.root_path%'
          - '%core.php_ext%'

    alfredoramos.share.controller.acp:
        class: alfredoramos\share\controller\acp
        arguments:
            - '@config'
            - '@template'
            - '@request'
            - '@language'
            - '@user'
            - '@log'
            - '@alfredoramos.share.helper'
